name: 🧭 Sitemap generator
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  sitemap-generator:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install modules
      run: yarn
      
    - name: Run sitemap generator
      run: yarn sitemap
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate sitemap"
